language: rust
rust:
  - stable
addons:
  mariadb: '10.0'
  apt:
    packages:
    - python
services: mariadb
before_script:
 - sh -c "mysql -e 'create database yayd'"
 - if [ ! -f "/tmp/ffmpeg-3.0.2-64bit-static/ffmpeg" ]; then wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz -O /tmp/ffmpeg.tar.xz ; fi
 - if [ ! -f "/tmp/ffmpeg-3.0.2-64bit-static/ffmpeg" ]; then tar xpvf "/tmp/ffmpeg.tar.xz" -C "/tmp/" ; fi
 - if [ ! -f "/tmp/ffmpeg-3.0.2-64bit-static/ffmpeg" ]; then chmod +x "/tmp/ffmpeg-3.0.2-64bit-static/ffmpeg" "/tmp/ffmpeg-3.0.2-64bit-static/ffprobe" "/tmp/ffmpeg-3.0.2-64bit-static/qt-faststart" ; fi
 - wget --no-check-certificate "https://yt-dl.org/downloads/latest/youtube-dl" -O "/tmp/youtube-dl"
 - chmod +x "/tmp/youtube-dl"
 - export PATH=$PATH:/tmp/
script:
 - cargo build
 - db_test=true db_ip="127.0.0.1" db_port="3306" db_user=root db_password="" db_db=yayd download_dir="/tmp" temp_dir="/tmp" mbps=100 ffmpeg_dir="/tmp/ffmpeg-3.0.2-64bit-static/" cargo test
cache:
  apt : true
  directories:
  - /tmp/ffmpeg-3.0.2-64bit-static/
sudo: false