language: rust
rust:
  - stable
addons:
  mariadb: '10.0'
  apt:
    packages:
    - youtube-dl
services: mariadb
before_script:
 - sh -c "mysql -e 'create database yayd'"
 - wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz -O /tmp/ffmpeg.tar.xz
 - tar xpvf "/tmp/ffmpeg.tar.xz" -C /tmp/
script:
 - cargo build
 - db_test=true db_ip="127.0.0.1" db_port="3306" db_user=root db_password="" db_db=yayd download_dir="/tmp" temp_dir="/tmp" mbps=100 ffmpeg_dir="/tmp/ffmpeg/ffmpeg-2.8.5-64bit-static/" cargo test
cache:
  directories:
  - /tmp/ffmpeg/ffmpeg-2.8.5-64bit-static/
sudo: false