[package]
name = "yayd-backend"
version = "0.0.4"
authors = ["Aron Heinecke <aron.heinecke@t-online.de>"]

[[bin]]
name = "yayd-backend"

#[profile.release]
#lto = true

[dependencies]
lazy_static = "0.1.15"
toml = "0.1.23"
rustc-serialize = "0.3.16"
log = "0.3.3"
log4rs = "0.3.3"
zip = "0.1.15"
#hyper = "0.3.13"

[dependencies.mysql]
mysql = "0.20.1"
default-features = false

[dependencies.regex]
regex = "0.1.41"
regex_macros = "0.1.21"
