[package]
name = "yayd-backend"
version = "0.0.1"
authors = ["Aron Heinecke"]

[[bin]]
name = "yayd-backend"

[dependencies.mysql]
mysql = "0.8.1"
default-features = false

[dependencies.lazy_static]
lazy_static = "0.1.10"

[dependencies.toml]
toml = "0.1.20"

[dependencies.regex]
regex = "0.1.27"
regex_macros = "0.1.15"

#[dependencies.hyper]
#hyper = "0.3.13"