[package]
name = "yayd-backend"
version = "0.0.2"
authors = ["Aron Heinecke <aron.heinecke@t-online.de"]

[[bin]]
name = "yayd-backend"

#[profile.release]
#lto = true

[dependencies.mysql]
mysql = "0.14.0"
default-features = false

[dependencies.lazy_static]
lazy_static = "0.1.11"

[dependencies.toml]
toml = "0.1.21"

[dependencies.regex]
regex = "0.1.41"
regex_macros = "0.1.21"

[dependencies.rustc-serialize]
rustc-serialize = "0.3.15"

#[dependencies.hyper]
#hyper = "0.3.13"