[package]
name = "yayd-backend"
version = "0.6.1"
authors = ["Aron Heinecke <Ox0p54r36@t-online.de>"]

[[bin]]
name = "yayd-backend"

#[profile.release]
#lto = true

[dependencies]
lazy_static = "0.1.15"
toml = "0.1.25"
rustc-serialize = "0.3.16"
log = "0.3.4"
log4rs = "0.3.3"
zip = "0.1.15"

[dependencies.mysql]
mysql = "1.20.1"
default-features = false

[dependencies.regex]
regex = "0.1.47"
regex_macros = "0.1.26"
