[package]
name = "yayd-backend"
version = "0.0.2"
authors = ["Aron Heinecke <aron.heinecke@t-online.de"]

[[bin]]
name = "yayd-backend"

#[profile.release]
#lto = true

[dependencies]
lazy_static = "0.1.11"
toml = "0.1.21"
rustc-serialize = "0.3.15"
log = "0.3.3"
fern = "*"
#hyper = "0.3.13"

[dependencies.mysql]
mysql = "0.14.0"
default-features = false

[dependencies.regex]
regex = "0.1.41"
regex_macros = "0.1.21"
